version: "3.9"

### MONGO DB SERVICE INSTALLATION GUIDES AND TIPS USING DOCKER
# https://medium.com/bb-tutorials-and-thoughts/develop-nodejs-rest-api-with-mongodb-using-docker-compose-df9a37287aed
# https://medium.com/rahasak/enable-mongodb-authentication-with-docker-1b9f7d405a94
# https://docs.mongodb.com/manual/tutorial/enable-authentication/

### NEO4J DB SERVICE INSTALLATION GUIDES AND TIPS USING DOCKER
# https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
# https://neo4j.com/docs/graph-data-science/current/installation/
# https://neo4j.com/docs/graph-data-science/current/installation/
# https://neo4j.com/developer/docker-run-neo4j/

### PYTHON-FLASK SERVICE INSTALLATION GUIDES AND TIPS USING DOCKER
# https://docs.docker.com/compose/gettingstarted/
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://stackoverflow.com/questions/60086741/docker-so-slow-while-installing-pip-requirements
# https://pythonspeed.com/articles/alpine-docker-python/
# https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container
# https://github.com/pallets/flask-sqlalchemy/issues/630
# https://stackoverflow.com/questions/20813486/exploring-docker-containers-file-system

### Importing test data
## Access smia CLI at working directory
# docker exec -t -i smia_user-interface_1 /bin/bash
## Run test driver
# python test_driver.py
## exit CLI
# python test_driver.py

### Running Reddit crawler
## Access smia cli at working directory
# docker exec -t -i smia_user-interface_1 /bin/bash
## Run reddit driver
# python reddit_driver.py
## exit CLI
# python test_driver.py

services:
  mongo-db:
    image: mongo:${mongo_db_version}
    restart: unless-stopped
    ports:
      - "${mongo_db_port}:27017"
    container_name: mongo-db
    volumes:
      - ./services/mongodb/db/data/db:/services/mongodb/db/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongo_db_user}
      - MONGO_INITDB_ROOT_PASSWORD=${mongo_db_pass}
    command: [--auth]

  neo4j-user-graph:
    image: neo4j:${neo4j_users_db_version}
    restart: unless-stopped
    ports:
      - "${neo4j_users_http_port}:7474"
      - "${neo4j_users_db_port}:7687"
    container_name: neo4j-user-graph
    volumes:
      - ./services/neo4j-users/conf:/services/conf
      - ./services/neo4j-users/data:/services/data
      - ./services/neo4j-users/import:/services/import
      - ./services/neo4j-users/logs:/services/logs
      - ./services/neo4j-users/plugins:/services/plugins
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=${neo4j_users_db_user}/${neo4j_users_db_pass}

  neo4j-activity-graph:
    image: neo4j:${neo4j_activities_db_version}
    restart: unless-stopped
    ports:
      - "${neo4j_activities_http_port}:7474"
      - "${neo4j_activities_db_port}:7687"
    container_name: neo4j-activity-graph
    volumes:
      - ./services/neo4j-activities/conf:/services/conf
      - ./services/neo4j-activities/data:/services/data
      - ./services/neo4j-activities/import:/services/import
      - ./services/neo4j-activities/logs:/services/logs
      - ./services/neo4j-activities/plugins:/services/plugins
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=${neo4j_activities_db_user}/${neo4j_activities_db_pass}

  user-interface:
    image: smia/ui:1.0.0
    restart: unless-stopped
    build: .
    depends_on:
      - mongo-db
      - neo4j-user-graph
      - neo4j-activity-graph
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: ${FLASK_ENV}