version: "3.9"

### MONGO DB SERVICE INSTALLATION GUIDES AND TIPS USING DOCKER
# https://medium.com/bb-tutorials-and-thoughts/develop-nodejs-rest-api-with-mongodb-using-docker-compose-df9a37287aed
# https://medium.com/rahasak/enable-mongodb-authentication-with-docker-1b9f7d405a94
# https://docs.mongodb.com/manual/tutorial/enable-authentication/

### NEO4J DB SERVICE INSTALLATION GUIDES AND TIPS USING DOCKER
# https://thibaut-deveraux.medium.com/how-to-install-neo4j-with-docker-compose-36e3ba939af0
# https://neo4j.com/docs/graph-data-science/current/installation/
# https://neo4j.com/docs/graph-data-science/current/installation/
# https://neo4j.com/developer/docker-run-neo4j/

### PYTHON-FLASK SERVICE INSTALLATION GUIDES AND TIPS USING DOCKER
# https://docs.docker.com/compose/gettingstarted/

services:
  mongo-db-service:
    image: mongo:${mongo_db_version}
    restart: unless-stopped
    ports:
      - "${mongo_db_port}:27017"
    container_name: mongo-db
    volumes:
      - ./services/mongodb/db/data/db:/services/mongodb/db/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongo_db_user}
      - MONGO_INITDB_ROOT_PASSWORD=${mongo_db_pass}
    command: [--auth]

  neo4j-user-graph-service:
    image: neo4j:${neo4j_users_db_version}
    restart: unless-stopped
    ports:
      - "${neo4j_users_http_port}:7474"
      - "${neo4j_users_db_port}:7687"
    volumes:
      - ./services/neo4j-users/conf:/services/conf
      - ./services/neo4j-users/data:/services/data
      - ./services/neo4j-users/import:/services/import
      - ./services/neo4j-users/logs:/services/logs
      - ./services/neo4j-users/plugins:/services/plugins
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=${neo4j_users_db_user}/${neo4j_users_db_pass}

  neo4j-activity-graph-service:
    image: neo4j:${neo4j_activities_db_version}
    restart: unless-stopped
    ports:
      - "${neo4j_activities_http_port}:7474"
      - "${neo4j_activities_db_port}:7687"
    volumes:
      - ./services/neo4j-activities/conf:/services/conf
      - ./services/neo4j-activities/data:/services/data
      - ./services/neo4j-activities/import:/services/import
      - ./services/neo4j-activities/logs:/services/logs
      - ./services/neo4j-activities/plugins:/services/plugins
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=${neo4j_activities_db_user}/${neo4j_activities_db_pass}